### ISSUE TITLE
Issue when running a gitscan

### ISSUE THREAD

**Issue by n0wond3r** [nsonaniya2010/SubDomainizer#26]
I'm running linux Mint tina

uname: 
Linux d0urd3n 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

This is the error I'm getting:

Traceback (most recent call last):
  File "/home/n0w0nd3r/tools/SubDomainizer/SubDomainizer.py", line 869, in <module>
    gitThread.map(getGithubData, contentApiURLs)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/n0w0nd3r/tools/SubDomainizer/SubDomainizer.py", line 617, in getGithubData
    _data = base64.b64decode(jsonData['content'])
KeyError: 'content'

**Comment by nsonaniya2010** [comment]
Can you share the screenshot with command?

**Comment by nsonaniya2010** [comment]
Also please  check if GitHub Personal Access token passed as an argument is valid or not.

**Comment by nsonaniya2010** [comment]
Closing issue as I didn't got reply from you.
